language: node_js
dist: trusty
sudo: false
node_js:
  - "6"
  - "7"
  - "8"

install:
  - npm install --only=dev

before_script:
  - ./node_modules/.bin/truffle develop --log --gasLimit 7500000 --gasPrice 2000 > /dev/null &
  - sleep 5

script:
  - ./node_modules/.bin/truffle compile &&
    ./node_modules/.bin/truffle test

notifications:
  email:
    on_success: change
    on_failure: always
